// Mocks generated by Mockito 5.4.6 from annotations
// in fluency_app/test/features/path/presentation/pages/path_page_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i6;
import 'dart:ui' as _i8;

import 'package:fluency_app/features/path/domain/usecases/get_learning_path.dart'
    as _i2;
import 'package:fluency_app/features/path/domain/usecases/reset_progress.dart'
    as _i3;
import 'package:fluency_app/features/path/presentation/controller/path_controller.dart'
    as _i5;
import 'package:fluency_app/features/path/presentation/controller/path_event.dart'
    as _i7;
import 'package:fluency_app/features/path/presentation/controller/path_state.dart'
    as _i4;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeGetLearningPath_0 extends _i1.SmartFake
    implements _i2.GetLearningPath {
  _FakeGetLearningPath_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeResetProgress_1 extends _i1.SmartFake implements _i3.ResetProgress {
  _FakeResetProgress_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakePathState_2 extends _i1.SmartFake implements _i4.PathState {
  _FakePathState_2(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [PathController].
///
/// See the documentation for Mockito's code generation for more information.
class MockPathController extends _i1.Mock implements _i5.PathController {
  MockPathController() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.GetLearningPath get getLearningPath =>
      (super.noSuchMethod(
            Invocation.getter(#getLearningPath),
            returnValue: _FakeGetLearningPath_0(
              this,
              Invocation.getter(#getLearningPath),
            ),
          )
          as _i2.GetLearningPath);

  @override
  _i3.ResetProgress get resetProgress =>
      (super.noSuchMethod(
            Invocation.getter(#resetProgress),
            returnValue: _FakeResetProgress_1(
              this,
              Invocation.getter(#resetProgress),
            ),
          )
          as _i3.ResetProgress);

  @override
  _i4.PathState get state =>
      (super.noSuchMethod(
            Invocation.getter(#state),
            returnValue: _FakePathState_2(this, Invocation.getter(#state)),
          )
          as _i4.PathState);

  @override
  _i6.Stream<_i4.PathState> get stream =>
      (super.noSuchMethod(
            Invocation.getter(#stream),
            returnValue: _i6.Stream<_i4.PathState>.empty(),
          )
          as _i6.Stream<_i4.PathState>);

  @override
  bool get hasListeners =>
      (super.noSuchMethod(Invocation.getter(#hasListeners), returnValue: false)
          as bool);

  @override
  void handleEvent(_i7.PathEvent? event) => super.noSuchMethod(
    Invocation.method(#handleEvent, [event]),
    returnValueForMissingStub: null,
  );

  @override
  void emit(_i4.PathState? newState) => super.noSuchMethod(
    Invocation.method(#emit, [newState]),
    returnValueForMissingStub: null,
  );

  @override
  void dispose() => super.noSuchMethod(
    Invocation.method(#dispose, []),
    returnValueForMissingStub: null,
  );

  @override
  void addListener(_i8.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#addListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void removeListener(_i8.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#removeListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void notifyListeners() => super.noSuchMethod(
    Invocation.method(#notifyListeners, []),
    returnValueForMissingStub: null,
  );
}
