// Mocks generated by Mockito 5.4.6 from annotations
// in fluency_app/test/features/lesson/presentation/controller/lesson_controller_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;

import 'package:dartz/dartz.dart' as _i3;
import 'package:fluency_app/core/errors/failures.dart' as _i6;
import 'package:fluency_app/features/path/domain/entities/lesson.dart' as _i7;
import 'package:fluency_app/features/path/domain/repositories/path_repository.dart'
    as _i2;
import 'package:fluency_app/features/path/domain/usecases/get_lesson.dart'
    as _i4;
import 'package:fluency_app/features/path/domain/usecases/update_lesson_progress.dart'
    as _i8;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakePathRepository_0 extends _i1.SmartFake
    implements _i2.PathRepository {
  _FakePathRepository_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeEither_1<L, R> extends _i1.SmartFake implements _i3.Either<L, R> {
  _FakeEither_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [GetLesson].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetLesson extends _i1.Mock implements _i4.GetLesson {
  MockGetLesson() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.PathRepository get repository =>
      (super.noSuchMethod(
            Invocation.getter(#repository),
            returnValue: _FakePathRepository_0(
              this,
              Invocation.getter(#repository),
            ),
          )
          as _i2.PathRepository);

  @override
  _i5.Future<_i3.Either<_i6.Failure, _i7.Lesson>> call(String? lessonId) =>
      (super.noSuchMethod(
            Invocation.method(#call, [lessonId]),
            returnValue: _i5.Future<_i3.Either<_i6.Failure, _i7.Lesson>>.value(
              _FakeEither_1<_i6.Failure, _i7.Lesson>(
                this,
                Invocation.method(#call, [lessonId]),
              ),
            ),
          )
          as _i5.Future<_i3.Either<_i6.Failure, _i7.Lesson>>);
}

/// A class which mocks [UpdateLessonProgress].
///
/// See the documentation for Mockito's code generation for more information.
class MockUpdateLessonProgress extends _i1.Mock
    implements _i8.UpdateLessonProgress {
  MockUpdateLessonProgress() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.PathRepository get repository =>
      (super.noSuchMethod(
            Invocation.getter(#repository),
            returnValue: _FakePathRepository_0(
              this,
              Invocation.getter(#repository),
            ),
          )
          as _i2.PathRepository);

  @override
  _i5.Future<_i3.Either<_i6.Failure, void>> call(
    _i8.UpdateLessonProgressParams? params,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#call, [params]),
            returnValue: _i5.Future<_i3.Either<_i6.Failure, void>>.value(
              _FakeEither_1<_i6.Failure, void>(
                this,
                Invocation.method(#call, [params]),
              ),
            ),
          )
          as _i5.Future<_i3.Either<_i6.Failure, void>>);
}
