// Mocks generated by Mockito 5.4.6 from annotations
// in fluency_app/test/features/lesson/presentation/pages/lesson_tasks_page_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i6;
import 'dart:ui' as _i8;

import 'package:fluency_app/features/lesson/presentation/controller/lesson_controller.dart'
    as _i5;
import 'package:fluency_app/features/lesson/presentation/controller/lesson_event.dart'
    as _i7;
import 'package:fluency_app/features/lesson/presentation/controller/lesson_state.dart'
    as _i4;
import 'package:fluency_app/features/path/domain/usecases/get_lesson.dart'
    as _i2;
import 'package:fluency_app/features/path/domain/usecases/update_lesson_progress.dart'
    as _i3;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeGetLesson_0 extends _i1.SmartFake implements _i2.GetLesson {
  _FakeGetLesson_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeUpdateLessonProgress_1 extends _i1.SmartFake
    implements _i3.UpdateLessonProgress {
  _FakeUpdateLessonProgress_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeLessonState_2 extends _i1.SmartFake implements _i4.LessonState {
  _FakeLessonState_2(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [LessonController].
///
/// See the documentation for Mockito's code generation for more information.
class MockLessonController extends _i1.Mock implements _i5.LessonController {
  MockLessonController() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.GetLesson get getLesson =>
      (super.noSuchMethod(
            Invocation.getter(#getLesson),
            returnValue: _FakeGetLesson_0(this, Invocation.getter(#getLesson)),
          )
          as _i2.GetLesson);

  @override
  _i3.UpdateLessonProgress get updateLessonProgress =>
      (super.noSuchMethod(
            Invocation.getter(#updateLessonProgress),
            returnValue: _FakeUpdateLessonProgress_1(
              this,
              Invocation.getter(#updateLessonProgress),
            ),
          )
          as _i3.UpdateLessonProgress);

  @override
  _i4.LessonState get state =>
      (super.noSuchMethod(
            Invocation.getter(#state),
            returnValue: _FakeLessonState_2(this, Invocation.getter(#state)),
          )
          as _i4.LessonState);

  @override
  _i6.Stream<_i4.LessonState> get stream =>
      (super.noSuchMethod(
            Invocation.getter(#stream),
            returnValue: _i6.Stream<_i4.LessonState>.empty(),
          )
          as _i6.Stream<_i4.LessonState>);

  @override
  bool get hasListeners =>
      (super.noSuchMethod(Invocation.getter(#hasListeners), returnValue: false)
          as bool);

  @override
  void handleEvent(_i7.LessonEvent? event) => super.noSuchMethod(
    Invocation.method(#handleEvent, [event]),
    returnValueForMissingStub: null,
  );

  @override
  void emit(_i4.LessonState? newState) => super.noSuchMethod(
    Invocation.method(#emit, [newState]),
    returnValueForMissingStub: null,
  );

  @override
  void dispose() => super.noSuchMethod(
    Invocation.method(#dispose, []),
    returnValueForMissingStub: null,
  );

  @override
  void addListener(_i8.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#addListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void removeListener(_i8.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#removeListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void notifyListeners() => super.noSuchMethod(
    Invocation.method(#notifyListeners, []),
    returnValueForMissingStub: null,
  );
}
