// Mocks generated by Mockito 5.4.6 from annotations
// in fluency_app/test/helpers/test_helper.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;

import 'package:dartz/dartz.dart' as _i2;
import 'package:fluency_app/core/errors/failures.dart' as _i6;
import 'package:fluency_app/features/path/data/datasources/path_local_datasource.dart'
    as _i10;
import 'package:fluency_app/features/path/data/datasources/path_mock_datasource.dart'
    as _i9;
import 'package:fluency_app/features/path/data/models/learning_path_model.dart'
    as _i3;
import 'package:fluency_app/features/path/domain/entities/learning_path.dart'
    as _i7;
import 'package:fluency_app/features/path/domain/entities/lesson.dart' as _i8;
import 'package:fluency_app/features/path/domain/repositories/path_repository.dart'
    as _i4;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeEither_0<L, R> extends _i1.SmartFake implements _i2.Either<L, R> {
  _FakeEither_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeLearningPathModel_1 extends _i1.SmartFake
    implements _i3.LearningPathModel {
  _FakeLearningPathModel_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [PathRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockPathRepository extends _i1.Mock implements _i4.PathRepository {
  MockPathRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<_i2.Either<_i6.Failure, _i7.LearningPath>> getLearningPath() =>
      (super.noSuchMethod(
            Invocation.method(#getLearningPath, []),
            returnValue:
                _i5.Future<_i2.Either<_i6.Failure, _i7.LearningPath>>.value(
                  _FakeEither_0<_i6.Failure, _i7.LearningPath>(
                    this,
                    Invocation.method(#getLearningPath, []),
                  ),
                ),
          )
          as _i5.Future<_i2.Either<_i6.Failure, _i7.LearningPath>>);

  @override
  _i5.Future<_i2.Either<_i6.Failure, void>> updateLessonProgress(
    String? lessonId,
    List<String>? completedTaskIds,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#updateLessonProgress, [
              lessonId,
              completedTaskIds,
            ]),
            returnValue: _i5.Future<_i2.Either<_i6.Failure, void>>.value(
              _FakeEither_0<_i6.Failure, void>(
                this,
                Invocation.method(#updateLessonProgress, [
                  lessonId,
                  completedTaskIds,
                ]),
              ),
            ),
          )
          as _i5.Future<_i2.Either<_i6.Failure, void>>);

  @override
  _i5.Future<_i2.Either<_i6.Failure, _i8.Lesson>> getLesson(String? lessonId) =>
      (super.noSuchMethod(
            Invocation.method(#getLesson, [lessonId]),
            returnValue: _i5.Future<_i2.Either<_i6.Failure, _i8.Lesson>>.value(
              _FakeEither_0<_i6.Failure, _i8.Lesson>(
                this,
                Invocation.method(#getLesson, [lessonId]),
              ),
            ),
          )
          as _i5.Future<_i2.Either<_i6.Failure, _i8.Lesson>>);

  @override
  _i5.Future<_i2.Either<_i6.Failure, void>> resetProgress() =>
      (super.noSuchMethod(
            Invocation.method(#resetProgress, []),
            returnValue: _i5.Future<_i2.Either<_i6.Failure, void>>.value(
              _FakeEither_0<_i6.Failure, void>(
                this,
                Invocation.method(#resetProgress, []),
              ),
            ),
          )
          as _i5.Future<_i2.Either<_i6.Failure, void>>);
}

/// A class which mocks [PathMockDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockPathMockDataSource extends _i1.Mock
    implements _i9.PathMockDataSource {
  MockPathMockDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<_i3.LearningPathModel> getMockPath() =>
      (super.noSuchMethod(
            Invocation.method(#getMockPath, []),
            returnValue: _i5.Future<_i3.LearningPathModel>.value(
              _FakeLearningPathModel_1(
                this,
                Invocation.method(#getMockPath, []),
              ),
            ),
          )
          as _i5.Future<_i3.LearningPathModel>);
}

/// A class which mocks [PathLocalDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockPathLocalDataSource extends _i1.Mock
    implements _i10.PathLocalDataSource {
  MockPathLocalDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<_i3.LearningPathModel?> getCachedPath() =>
      (super.noSuchMethod(
            Invocation.method(#getCachedPath, []),
            returnValue: _i5.Future<_i3.LearningPathModel?>.value(),
          )
          as _i5.Future<_i3.LearningPathModel?>);

  @override
  _i5.Future<void> cachePath(_i3.LearningPathModel? path) =>
      (super.noSuchMethod(
            Invocation.method(#cachePath, [path]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> cacheTaskProgress(
    String? lessonId,
    List<String>? completedTaskIds,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#cacheTaskProgress, [lessonId, completedTaskIds]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<List<String>?> getCompletedTaskIds(String? lessonId) =>
      (super.noSuchMethod(
            Invocation.method(#getCompletedTaskIds, [lessonId]),
            returnValue: _i5.Future<List<String>?>.value(),
          )
          as _i5.Future<List<String>?>);

  @override
  _i5.Future<void> clearAllProgress() =>
      (super.noSuchMethod(
            Invocation.method(#clearAllProgress, []),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> cacheLessonStatus(String? lessonId, String? status) =>
      (super.noSuchMethod(
            Invocation.method(#cacheLessonStatus, [lessonId, status]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<String?> getLessonStatus(String? lessonId) =>
      (super.noSuchMethod(
            Invocation.method(#getLessonStatus, [lessonId]),
            returnValue: _i5.Future<String?>.value(),
          )
          as _i5.Future<String?>);
}
